# This file was generated by GoReleaser. DO NOT EDIT.
class Toyotter < Formula
  desc "CUI based Twitter client for Golang"
  homepage "https://github.com/ksk001100/toyotter"
  version "0.5.6"

  if OS.mac?
    url "https://github.com/ksk001100/toyotter/releases/download/v0.5.6/toyotter_0.5.6_macOS_x86_64.tar.gz"
    sha256 "1831075a879ed92a94d54f66fc11c276df4be1ca5ede2457b71836095b9bef51"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ksk001100/toyotter/releases/download/v0.5.6/toyotter_0.5.6_Linux_x86_64.tar.gz"
      sha256 "f5a9bd9f4425617f3eceb79f0356b815c2ded1efd20d9939f5cc55f9fc7695ab"
    end
  end
  
  depends_on "fzf"

  def install
    bin.install 'toyotter'
  end
end
