# This file was generated by GoReleaser. DO NOT EDIT.
class Toyotter < Formula
  desc "CUI based Twitter client for Golang"
  homepage "https://github.com/ksk001100/toyotter"
  version "0.5.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/ksk001100/toyotter/releases/download/v0.5.5/toyotter_0.5.5_macOS_x86_64.tar.gz"
    sha256 "459f03c25de168d930f545eefbc13d7a1d2217c940599cc9a95a0f5fd1aeec3a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/ksk001100/toyotter/releases/download/v0.5.5/toyotter_0.5.5_Linux_x86_64.tar.gz"
      sha256 "f9045a00579eba7f3d93b5e145558309d8892fda9bd493d164e2141253f9c798"
    end
  end
  
  depends_on "fzf"

  def install
    bin.install 'toyotter'
  end
end
