# This file was generated by GoReleaser. DO NOT EDIT.
class Toyotter < Formula
  desc "CUI based Twitter client for Golang"
  homepage "https://github.com/KeisukeToyota/toyotter"
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/KeisukeToyota/toyotter/releases/download/v0.4.0/toyotter_0.4.0_Darwin_x86_64.tar.gz"
    sha256 "707b849fcd2048a366b732cbe5c6055ac9ced15d79b215e5a145d302c119bf39"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/KeisukeToyota/toyotter/releases/download/v0.4.0/toyotter_0.4.0_Linux_x86_64.tar.gz"
      sha256 "796c9dca160b7c34a09366bcaef9a12d876fff78242f2db808abdbe611af105d"
    end
  end
  
  depends_on "fzf"

  def install
    bin.install 'toyotter'
  end
end
